version: '3.8'

services:
  frontend:
    image: mibitech-frontend:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mibitech-frontend.rule=Host(`appteste.mibitech.com.br`)"
        - "traefik.http.routers.mibitech-frontend.entrypoints=websecure"
        - "traefik.http.routers.mibitech-frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.mibitech-frontend.loadbalancer.server.port=3000"
        - "traefik.http.routers.mibitech-frontend.priority=10"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true