version: "3.7"
services:
  site_mibitech_django:
    image: site_mibitech_django:latest
    volumes:
      - site_mibitech_django_data:/app
    networks:
      - network_public
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=site_mibitech.mibitech.com.br
      - VIRTUAL_HOST=site_mibitech.mibitech.com.br
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.site_mibitech_django.rule=Host(`site_mibitech.mibitech.com.br`)
        - traefik.http.routers.site_mibitech_django.entrypoints=websecure
        - traefik.http.routers.site_mibitech_django.tls.certresolver=letsencryptresolver
        - traefik.http.routers.site_mibitech_django.service=site_mibitech_django
        - traefik.http.services.site_mibitech_django.loadbalancer.server.port=8000
        - traefik.http.services.site_mibitech_django.loadbalancer.passHostHeader=true

  site_mibitech_nginx:
    image: site_mibitech_nginx:latest
    volumes:
      - site_mibitech_nginx_data:/var/log/nginx
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.site_mibitech_nginx.rule=Host(`nginx-site_mibitech.mibitech.com.br`)
        - traefik.http.routers.site_mibitech_nginx.entrypoints=websecure
        - traefik.http.routers.site_mibitech_nginx.tls.certresolver=letsencryptresolver
        - traefik.http.routers.site_mibitech_nginx.service=site_mibitech_nginx
        - traefik.http.services.site_mibitech_nginx.loadbalancer.server.port=80
        - traefik.http.services.site_mibitech_nginx.loadbalancer.passHostHeader=true

volumes:
  site_mibitech_django_data:
    external: true
    name: site_mibitech_django_data
  site_mibitech_nginx_data:
    external: true
    name: site_mibitech_nginx_data

networks:
  network_public:
    name: network_public
    external: true