version: '3.7'

# Use um nome de projeto específico para evitar conflitos
name: mibitech

services:
  # Não precisamos definir o Traefik aqui, pois já está rodando no servidor

  backend:
    build: ./backend
    image: mibitech-backend:latest
    volumes:
      - ./backend:/app
      - backend_static:/app/static
    networks:
      - network_public
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,site.mibitech.com.br
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mibitech_backend.rule=Host(`site.mibitech.com.br`) && (PathPrefix(`/api`) || PathPrefix(`/admin`))"
        - "traefik.http.routers.mibitech_backend.entrypoints=websecure"
        - "traefik.http.routers.mibitech_backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.mibitech_backend.loadbalancer.server.port=8000"
        - "traefik.http.services.mibitech_backend.loadbalancer.passHostHeader=true"

  frontend:
    build: ./frontend
    image: mibitech-frontend:latest
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mibitech_frontend.rule=Host(`site.mibitech.com.br`)"
        - "traefik.http.routers.mibitech_frontend.entrypoints=websecure"
        - "traefik.http.routers.mibitech_frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.mibitech_frontend.loadbalancer.server.port=3000"
        - "traefik.http.services.mibitech_frontend.loadbalancer.passHostHeader=true"
        - "traefik.http.routers.mibitech_frontend.priority=1"

# Configuração para Docker Swarm
# Para implantar: docker stack deploy -c docker-compose.yml mibitech
    name: mibitech_backend_static

networks:
  network_public:
    external: true
    name: network_public

volumes:
  backend_static: