version: '3.8'

services:
  api:
    image: mibitech-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Mfcd62!!@server.mibitech.com.br:5432/mibitech
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - ENVIRONMENT=development
      - CORS_ORIGINS=*
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`apirest.mibitech.com.br`)"
        - "traefik.http.services.backend.loadbalancer.server.port=8000"
        - "traefik.http.routers.backend.entrypoints=web,websecure"
        - "traefik.http.routers.backend-appteste.rule=Host(`appteste.mibitech.com.br`) && PathPrefix(`/api`)"
        - "traefik.http.services.backend-appteste.loadbalancer.server.port=8000"
        - "traefik.http.routers.backend-appteste.entrypoints=web,websecure"
    networks:
      - traefik-public
    restart: always

networks:
  traefik-public:
    external: true