version: '3.8'

services:
  api:
    image: mibitech-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - ENVIRONMENT=development
      - CORS_ORIGINS=*
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`apirest.mibitech.com.br`)"
        - "traefik.http.services.backend.loadbalancer.server.port=8000"
        - "traefik.http.routers.backend.entrypoints=web,websecure"
        - "traefik.http.routers.backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE"
        - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowheaders=*"
        - "traefik.http.middlewares.cors-headers.headers.accesscontrolalloworiginlist=*"
        - "traefik.http.middlewares.cors-headers.headers.accesscontrolmaxage=100"
        - "traefik.http.middlewares.cors-headers.headers.addvaryheader=true"
        - "traefik.http.routers.backend.middlewares=cors-headers@docker"
        # Removendo o middleware que remove o prefixo /api, pois a aplicação espera esse prefixo
        # - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
        - "traefik.http.routers.backend-api.rule=Host(`apirest.mibitech.com.br`) && PathPrefix(`/api/`)"
        - "traefik.http.services.backend-api.loadbalancer.server.port=8000"
        - "traefik.http.routers.backend-api.entrypoints=web,websecure"
        - "traefik.http.routers.backend-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.middlewares.backend-api-headers.headers.customrequestheaders.X-Forwarded-Prefix=/api"
        - "traefik.http.middlewares.cors-api.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE"
        - "traefik.http.middlewares.cors-api.headers.accesscontrolallowheaders=*"
        - "traefik.http.middlewares.cors-api.headers.accesscontrolalloworiginlist=*"
        - "traefik.http.middlewares.cors-api.headers.accesscontrolmaxage=100"
        - "traefik.http.middlewares.cors-api.headers.addvaryheader=true"
        - "traefik.http.routers.backend-api.middlewares=backend-api-headers@docker,cors-headers@docker"
        - "traefik.http.routers.backend-api.priority=20"
    networks:
      - network_public
    restart: always

networks:
  network_public:
    external: true