version: '2'

services:
  api:
    image: mibitech-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Mfcd62!!@server.mibitech.com.br:5432/mibitech
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - ENVIRONMENT=development
      - CORS_ORIGINS=*
    restart: always