version: '3.8'

services:
  api:
    image: mibitech-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Mfcd62!!Mfcd62!!@server.mibitech.com.br:5432/mibitech
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - ENVIRONMENT=development
      - CORS_ORIGINS=*
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`api.mibitech.com.br`)"
        - "traefik.http.services.backend.loadbalancer.server.port=8000"
        - "traefik.http.routers.backend.entrypoints=web,websecure"
    networks:
      - public-network
    restart: always

networks:
  public-network:
    external: true