version: '3.7'

services:
  backend:
    build: ./backend
    image: mibitech-backend:local
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - VIRTUAL_HOST=localhost
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    image: mibitech-frontend:local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
      - VIRTUAL_HOST=localhost
    command: node server.js

volumes:
  node_modules:

# Para executar: docker-compose -f docker-compose.local.yml up
# Para reconstruir: docker-compose -f docker-compose.local.yml up --build