version: '3.8'

services:
  api:
    image: mibitech-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Mfcd62!!Mfcd62!!@server.mibitech.com.br:5432/mibitech
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - ENVIRONMENT=development
      - CORS_ORIGINS=*
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`apirest.mibitech.com.br`)"
        - "traefik.http.services.backend.loadbalancer.server.port=8000"
        - "traefik.http.routers.backend.entrypoints=web,websecure"
        - "traefik.http.routers.backend-api.rule=Host(`apirest.mibitech.com.br`) && PathPrefix(`/api`)"
        - "traefik.http.services.backend-api.loadbalancer.server.port=8000"
        - "traefik.http.routers.backend-api.entrypoints=web,websecure"
        - "traefik.http.middlewares.backend-api-headers.headers.customrequestheaders.X-Forwarded-Prefix=/api"
        - "traefik.http.routers.backend-api.middlewares=backend-api-headers@docker"
        - "traefik.http.routers.backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.backend-api.tls.certresolver=letsencryptresolver"
        # Removendo o middleware que remove o prefixo /api, pois a aplicação espera esse prefixo
        # - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
        # - "traefik.http.routers.backend-api.middlewares=strip-api-prefix@docker"
    networks:
      - network_public
    restart: always

networks:
  network_public:
    external: true