# Este arquivo não é mais necessário, pois estamos usando a configuração do Traefik existente no servidor
# As configurações de roteamento agora são definidas como labels no docker-compose.yml

# Mantido apenas como referência
http:
  routers:
    mibitech_frontend:
      rule: "Host(`site.mibitech.com.br`)"
      service: "mibitech_frontend"
      entryPoints:
        - websecure
      priority: 10
      tls:
        certResolver: letsencryptresolver
    
    mibitech_backend_api:
      rule: "Host(`site.mibitech.com.br`) && PathPrefix(`/api`)"
      service: "mibitech_backend"
      entryPoints:
        - websecure
      priority: 20
      tls:
        certResolver: letsencryptresolver
    
    mibitech_backend_admin:
      rule: "Host(`site.mibitech.com.br`) && PathPrefix(`/admin`)"
      service: "mibitech_backend"
      entryPoints:
        - websecure
      priority: 20
      tls:
        certResolver: letsencryptresolver

  services:
    mibitech_frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"
    
    mibitech_backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"