http:
  routers:
    frontend:
      rule: "Host(`site.mibitech.com.br`)"
      service: "frontend"
      entryPoints:
        - web
      priority: 10
      # Adiciona informações específicas para este site
      middlewares:
        - mibitech-strip-prefix
    
    backend-api:
      rule: "Host(`site.mibitech.com.br`) && PathPrefix(`/api`)"
      service: "backend"
      entryPoints:
        - web
      priority: 20
      middlewares:
        - mibitech-strip-prefix
      middlewares:
        - mibitech-strip-prefix
    
    backend-admin:
      rule: "Host(`site.mibitech.com.br`) && PathPrefix(`/admin`)"
      service: "backend"
      entryPoints:
        - web
      priority: 20

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"
    
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"

  middlewares:
    mibitech-strip-prefix:
      stripPrefix:
        prefixes:
          - "/mibitech"
        forceSlash: true