"""create mensagem table

Revision ID: 5890837d8efc
Revises: 20250405_create_social_media
Create Date: 2025-04-07 18:41:42.184219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5890837d8efc'
down_revision = '20250405_create_social_media'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    if 'mensagem' not in inspector.get_table_names():
        op.create_table('mensagem',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('snome', sa.String(length=50)),
        sa.Column('semail', sa.String(length=50)),
        sa.Column('stelefone', sa.String(length=14)),
        sa.Column('sassunto', sa.String(length=30)),
        sa.Column('smensagem', sa.String(length=400))
        )
    with op.batch_alter_table('social_media', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nome da plataforma de mídia social',
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               comment='URL completa para o perfil na mídia social',
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=50),
               comment="Nome do ícone para exibição (ex: 'facebook', 'twitter')",
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='Data e hora de criação do registro',
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='Data e hora da última atualização',
               existing_nullable=False)
        batch_op.drop_index('ix_social_media_name')
        batch_op.create_index(batch_op.f('ix_social_media_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_media_id'))
        batch_op.create_index('ix_social_media_name', ['name'], unique=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='Data e hora da última atualização',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='Data e hora de criação do registro',
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Nome do ícone para exibição (ex: 'facebook', 'twitter')",
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='URL completa para o perfil na mídia social',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nome da plataforma de mídia social',
               existing_nullable=False)

    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), primary_key=True, index=True),
    sa.Column('snome', sa.String(length=50)),
    sa.Column('semail', sa.String(length=50)),
    sa.Column('stelefone', sa.String(length=14)),
    sa.Column('sassunto', sa.String(length=30)),
    sa.Column('smensagem', sa.String(length=400))
    )
    # ### end Alembic commands ###